accounts/urls.py
from django.conf.urls import url
from accounts.views import login_view, register_view, logout_view

app_name = 'accounts'

urlpatterns = [
    # login page
    url(r'^login/', login_view, name="login"),
    # logout page
    url(r'^logout/', logout_view, name="logout"),
    # register page
    url(r'^register/', register_view, name="register"),
]

bse/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    # website url
    url(r'^', include('buysell.urls')),

    # accounts app for login, register, logout
    url(r'^', include('accounts.urls')),

    # admin
    url(r'^admin/', admin.site.urls),

    # reset password auth contrib urls
    url(r'^password_reset/$', password_reset, {'template_name': 'accounts/password_reset_form.html'}, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    # /password_reset/confirm/base64_unique_id/token
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name': 'accounts/password_reset_confirm.html' }, name='password_reset_confirm'),
    url(r'^password_reset/complete/$', password_reset_complete, {'template_name': 'accounts/password_reset_complete.html'},name='password_reset_complete'),
]

# static uploaded files media url
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buysell/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'buysell'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^product/add/$', login_required(views.ProductCreate.as_view()), name='product_add'),
    url(r'^product/list/$', login_required(views.UserProductView.as_view()), name='user_product'),
    # e.g: /product/3/exit, restricted to logged in users only
    url(r'^product/(?P<pk>[0-9]+)/edit/$', login_required(views.ProductUpdate.as_view()), name='product_update'),
    # e.g: /product/3/delete, restricted to logged in users only
    url(r'^product/(?P<pk>[0-9]+)/delete/$', login_required(views.ProductDelete.as_view()), name='product_delete'),
]

buysell/models.py
from django.db import models
from django.urls import reverse
# multiple select field contrib
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User

# Product category such as shoes, clothes, tablets, etc...
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

# Product model
class Product(models.Model):
    # types of products: buy, sell, exchange
    BUY_SELL_EXCHANGE = (
        ('buy', 'Buy'),
        ('sell', 'Sell'),
        ('exchange', 'Exchange'),
    )
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.FileField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_type = MultiSelectField(choices=BUY_SELL_EXCHANGE, verbose_name="Product Type")
    description = models.TextField(verbose_name="Enter description and contact infos")
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    # where to redirect after model submit
    def get_absolute_url(self):
        return reverse('buysell:index')

    def __str__(self):
        return self.name

buysell/views.py
import operator
from functools import reduce
from django.shortcuts import render
from django.http import Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import Product, Category

# home page and search view
class IndexView(generic.ListView):
    template_name = 'buysell/index.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        # add list of categories to context of buysell index view
        context['categories'] = Category.objects.all()
        # get selected categories to maintain selection after submit
        context['q_category'] = self.request.GET.getlist('category')
        context['q_type'] = self.request.GET.getlist('type')
        context['q_keyword'] = self.request.GET.get('keyword') if self.request.GET.get('keyword') else ''
        return context

    def get_queryset(self):
        # prepare paramaters for query
        category = self.request.GET.getlist('category')
        keyword = self.request.GET.get('keyword')
        product_type = self.request.GET.getlist('type')

        # build up query filter for search view
        filters = Q(name__isnull = False)
        if category:
            filters = filters & Q(category__in = category)
        if keyword:
            filters = filters & Q(name__contains = keyword)
        if product_type:
            filters = filters & reduce(operator.or_, (Q(product_type__contains = item) for item in product_type))
        products_list = Product.objects.filter(filters).order_by('-modified_date')

        # add pagination to search results
        paginator = Paginator(products_list, 10)
        page = self.request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        return products

# list of products created/added by current user for dashboard
class UserProductView(generic.ListView):
    template_name = 'buysell/user_product.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(author=self.request.user,).order_by('-modified_date')

# product create form for logged in users
class ProductCreate(CreateView):
    model = Product
    fields = ['name','price','image','category','product_type','description']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super(ProductCreate, self).form_valid(form)

# product updated by user
class ProductUpdate(UpdateView):
    model = Product
    fields = ['name','price','image','category','product_type','description']
    success_url = reverse_lazy('buysell:user_product')

    def get_object(self):
        # prevent non authorised users to edit product
        obj = super(ProductUpdate, self).get_object()
        if not obj.author == self.request.user:
            raise Http404
        return obj

class ProductDelete(DeleteView):
    model = Product
    # redirect url after delete confirmation
    success_url = reverse_lazy('buysell:user_product')

    def get_object(self):
        # prevent non authorised users to delete product
        obj = super(ProductDelete, self).get_object()
        if not obj.author == self.request.user:
            raise Http404
        return obj

buysell/templates/buysell/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}BuySellExchange{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Euphoria+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" /> {% load static %}
    <link rel="stylesheet" href="{% static 'buysell/style.css' %}" />
</head>

<body>
    <nav class="navbar navbar-toggleable-md navbar-light bg- navbar-bottom">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand font-logo" href="{% url 'buysell:index' %}">BuySellExchange</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item m-1">
                    <a class="btn btn-outline-info my-2 my-sm-0" href="{% url 'buysell:product_add' %}">Add Product</a>
                </li>
                <li class="nav-item m-1">
                    <a class="btn btn-outline-primary my-2 my-sm-0" href="{% url 'buysell:user_product' %}">My Products</a>
                </li>
                <li class="nav-item m-1">
                    <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item m-1">
                    <a class="btn btn-outline-primary my-2 my-sm-0" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item m-1">
                    <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'accounts:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div id="wrapper">
        {% block content %} {% endblock %}
        <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page"
            data-toggle="tooltip" data-placement="left">
            <span class="fa fa-chevron-up"></span>
        </a>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
    <script src="{% static 'buysell/script.js' %}"></script>
</body>

</html>

buysell/templates/buysell/form.html
<!-- Generic reusable form fields display -->
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1 class="text-center text-primary">{{ title }}</h1>
                    {% if form.errors %} 
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %} 
                    {% endif %}
                    <form class="form-horizontal bg-faded p-2" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} 
                        {% for field in form %}
                            <div class="form-group">
                                <label class="control-label col-sm-12">
                                    {{ field.label_tag }}
                                </label>
                                <div class="col-sm-10">{{ field }}</div>
                                <div class="col-sm-offset-2 sol-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

buysell/templates/buysell/index.html
{% extends 'buysell/base.html' %} 
{% block content %}
<div class="row no-gutters">
    <div class="col-md-3">
        <form method="get" id="search-form" action="{% url 'buysell:index' %}">
            <input type="hidden" id="page" name="page" value="1" />
            <div class="row no-gutters m-3">
                <div class="col-md-12 text-center">
                    <div class="form-inline mb-1">
                        <input name="keyword" class="form-control" id="search-keyword" type="text" placeholder="Search" value="{{ q_keyword }}">
                        <button class="btn btn-outline-success" id="btn-search" type="submit">
                            <i class="fa fa-search"></i>
                            </i>
                        </button>
                    </div>
                    <button type="button" class="btn btn-type btn-sm btn{% if 'buy' not in q_type %}-outline{% endif %}-warning my-2 my-sm-0 btn-checkbox-type" name="buy">
                        <input {% if "buy" in q_type %}checked="checked" {% endif %} type="checkbox" name="type" value="buy" style="display:none;">Buy
                    </button>
                    <button type="button" class="btn btn-type btn-sm btn{% if 'sell' not in q_type %}-outline{% endif %}-warning my-2 my-sm-0 btn-checkbox-type" name="sell">
                        <input {% if "sell" in q_type %}checked="checked" {% endif %} type="checkbox" name="type" value="sell" style="display:none;">Sell
                    </button>
                    <button type="button" class="btn btn-type btn-sm btn{% if 'exchange' not in q_type %}-outline{% endif %}-warning my-2 my-sm-0 mb-1 btn-checkbox-type">
                        <input {% if "exchange" in q_type %}checked="checked" {% endif %} type="checkbox" name="type" value="exchange" style="display:none;">Exchange
                    </button>
                </div>
            </div>
            <div class="list-group">
                {% for category in categories %}
                <a href="#" class="checkbox-category list-group-item {% if category.id|stringformat:'i' in q_category %}active{% endif %}">
                    <input {% if category.id|stringformat:'i' in q_category %}checked="checked" {% endif %} type="checkbox" name="category" value="{{ category.id }}" style="display:none;"> {{ category.name }}
                </a>
                {% endfor %}
            </div>
        </form>
    </div>
    <div class="col-md-8">
        {% if products %}
            <div class="card-columns">
                {% for product in products %}
                <div class="card">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">{{ product.name }}</h4>
                        <p class="card-text">{{ product.description }}</p>
                        <p class="card-text">
                            <b class="text-muted text-success">Rs {{ product.price|floatformat:2 }}</b> ({{product.product_type}})</p>
                        <p class="card-text">
                            <small>{{ product.modified_date }}</small>
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="pagination">
                        {% if products.has_previous %}
                        <button class="btn-paginate btn btn-sm btn-outline-primary" data-page="{{ products.previous_page_number }}">Prev</button>
                        {% endif %} {% for page in products.paginator.page_range %}
                        <button class="btn-paginate btn btn-sm {% if products.number == page  %}btn-primary{% else %}btn-outline-primary{% endif %}"
                            data-page="{{ page }}">{{ page }}</button>
                        {% endfor %} {% if products.has_next %}
                        <button class="btn btn-sm btn-outline-primary btn-paginate" data-page="{{ products.next_page_number }}">Next</button>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% else %}
            <h1 class="text-danger text-center"> No results found </h1>
        {% endif %}
    </div>
</div>
{% endblock %}

buysell/templates/buysell/product_confirm_delete.html
{% extends 'buysell/base.html' %} 
{% block content %}
<form action="" method="post">{% csrf_token %}
    <h2>Are you sure you want to delete "{{ object }}"?</h2>
    <input class="btn btn-danger" type="submit" value="Confirm" />
    <a href="{% url 'buysell:user_product' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

buysell/templates/buysell/product_form.html
{% extends 'buysell/base.html' %} 
{% block title %}Add a new Product{% endblock %} 
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1 class="text-center text-primary">Add a new Product</h1>
                    {% include 'buysell/form.html' %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

buysell/templates/buysell/user_product.html
{% extends 'buysell/base.html' %} 
{% block content %} 
  {% if products %}
    <table class="table">
      <thead>
        <tr>
          <th>Product Name</th>
          <th>Last Updated</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
        <tr>
          <td>{{ product.name }}</td>
          <td>{{ product.modified_date }}</td>
          <td>
            <a href="{% url 'buysell:product_update' product.pk %}" class="btn btn-primary">
              <i class="fa fa-pencil"></i>
            </a>
          </td>
          <td>
            <a class="btn btn-danger" href="{% url 'buysell:product_delete' product.pk %}">
              <i class="fa fa-trash"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <h3 class="text-center">No products. Click <a href="{% url 'buysell:product_add' %}">here</a> to add a product.</h3> 
  {% endif %} 
{% endblock %}